# Generated by Django 3.1.3 on 2020-12-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
